### ISSUE TITLE
Event queue bug

### ISSUE THREAD

**Issue by viluon** [gamax92/cclite#19]
The event queue does not behave like the native/vanilla one. With vanilla CC, it is possible to create a scenario where the program adds a new event to the end of the event queue through os.queueEvent (let's call this event the endQueue event) and pulls events with os.pullEvent. When it reaches endQueue it can queue it again, thus creating a theoretically infinite event queue and ensuring there is always at least one event to pull. I use this principle myself in games and [vBenchmark](http://www.computercraft.info/forums2/index.php?/topic/23521-vbenchmark-the-ultimate-benchmarking-tool/). This scenario, when used in CCLite, can _horribly lag the emulator or crash it entirely_. Here is an example script:
```Lua
local endQueued=false

while true do
  if not endQueued then
    os.queueEvent("endOfQueue")
    endQueued=true
  end
  
  local ev={os.pullEvent()}
  if ev[1]=="endOfQueue" then
    endQueued=false
  end
end

```
This code run on CCLite Frames 64bit with Windows 7 Ultimate 64bit makes the emulator stop responding:boom::
![Screenshot](https://i.gyazo.com/09721295e990e9c7743d0856d17b5f61.png)

Please
- [ ] Fix this

**Comment by ds84182** [comment]
This is caused by code in main.lua that loops and resumes the coroutine
until the event queue is empty. To fix this, gamax would have to measure
the number of resumes done and stop it after a certain number.

**Comment by PixelToast** [comment]
Another solution is to put each computer in its own thread and check for a shutdown signal between pulled events

**Comment by viluon** [comment]
For programmers using CCLite, it is possible to bypass this bug without losing the advantages of the scenario described above by setting a timer to zero seconds and using it instead of the custom event. This drastically decreases FPS of the program but does not crash the emulator. A hybrid solution is to switch to this 'compatibility mode' only when the global `cclite` is set. This setting can be turned off in the CCLite configuration, however.

**Comment by gamax92** [comment]
This should be fixed now.

**Comment by viluon** [comment]
*bump* please reopen this @gamax92, still doesn't work (using the latest build from [your page](http://gamax92.pc-logix.com/cclite.html) ). Did you test this? :?

**Comment by gamax92** [comment]
I did test this and it didn't freeze as described.

**Comment by gamax92** [comment]
Releases have been completely redone and should be entirely updated now.

**Comment by viluon** [comment]
can confirm, latest Win x64 release works as advertised! Good job :+1:
